version: '3.8'

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: M1n0T4ur0
  #     POSTGRES_DB: incasso
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["pnpm", "dev"]

volumes:
  postgres_data: