const CLIENT_STATUS = {
  PENDING: "pending",
  ACTIVE: "active",
  INACTIVE: "inactive",
};

const TOKEN_TYPES = {
  INVITE_USER: "invite_user",
  RESET_PASSWORD: "reset_password",
  VERIFY_EMAIL: "verify_email",
  INVITE_COMPANY: "invite_company",
};

const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  TENANT_ADMIN: "TENANT_ADMIN",
  COLLECTIONS_EXECUTIVE: "COLLECTIONS_EXECUTIVE",
  DEBTOR: "DEBTOR",
  BAILIFF: "BAILIFF",
};

const COLLECTION_STATUS = {
  INITIAL: "initial",
  AANMANING: "aanmaning",
  SOMMATIE: "sommatie",
  INGEBREKESTELLING: "ingebrekestelling",
};

const PAYMENT_APPLICATION_STATUS = {
  PENDING: "PENDING",
  CAPITAL: "CAPITAL",
  INTEREST: "INTEREST",
  TAX: "TAX",
  CLIENT_COLLECTION_FEE: "CLIENT_COLLECTION_FEE",
  CLIENT_ABB_FEE: "CLIENT_ABB_FEE",
  ADMIN_COLLECTION_FEE: "ADMIN_COLLECTION_FEE",
  ADMIN_ABB_FEE: "ADMIN_ABB_FEE",
};

export { CLIENT_STATUS, TOKEN_TYPES, ROLES, COLLECTION_STATUS, PAYMENT_APPLICATION_STATUS };
